name = "jordan_pick"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["JordanPick", "Rado"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[lean_lib]]
name = "JordanPick"

[[lean_lib]]
name = "Rado"

[[lean_lib]]
name = "Uniformization"
