name = "jordan_pick"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["JordanPick", "Rado"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "360da6fa66c1273b76b6b2d8c5666fd5ac2e3b56"

[[lean_lib]]
name = "JordanPick"

[[lean_lib]]
name = "Rado"

[[lean_lib]]
name = "Uniformization"
